config/routes.rb
Rails.application.routes.draw do
  # root 'posts#show'
  root to: 'posts#index'

  post '/posts', to: 'posts#create'
  delete 'posts/:id', to: 'posts#destroy', as: :delete_post

  resources :posts
  resources :users

  get 'login', to: 'sessions#new'
  resource :session, only: %i[new create destroy]

  get '/user/dashboard', to: 'users#dashboard', as: 'user_dashboard'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  def self.recovery_password
  end

  has_many :posts, dependent: :destroy
  validates :name, :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    p @posts
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to user_dashboard_path
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_dashboard_path
  end

  private
  def post_params
    params.require(:posts).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:login])&.authenticate(params[:password])

    if user.present?
      session[:user_id] = user.id

      redirect_to user_dashboard_path, notice: 'You successfully logged in'
    else
      flash.now[:alert] = 'Wrong email or password'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: 'You successfully logged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  def create
    user_params = params.require(:user).permit(:name, :email, :password)

    user = User.create(user_params)
    session[:user_id] = user.id

    redirect_to user_dashboard_path, notice: 'Successful registration'
  end

  def edit
  end

  def dashboard
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Julia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@rails/ujs@6.0.2/lib/assets/compiled/rails-ujs.js" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

  <body>
    <div class="wrapper">
      <div class="navbar">
        <p class="title-sm text-bold">
          <%= link_to 'All posts', posts_path %>
        </p>
        <div>
          <% if current_user.present? %>
            <%= "@#{current_user.name}" %>
            <%=button_to 'Logout', session_path, method: :delete %>
          <% else %>
            <%= link_to 'Registration', new_user_path, class: 'button button-yellow mr-sm' %>
            <%= link_to 'Login', login_path, class: 'button button-yellow' %>
          <% end %>
        </div>
      </div>
    </div>

    <% if flash[:notice].present? %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <% if flash[:alert].present? %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container-md">
  <h1 class="text-center fs-1">Post edit</h1>
  <%= form_for(@post) do |form| %>
    <div class="form-group">
      <%= form.label :text %>
      <%= form.text_field :text, class:'form-control' %>
    </div>
    <%= submit_tag "Update", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="m-5">
  <h1>Posts</h1>
  <% @posts.each do |post| %>
    <div class="m-3">
      <%= post.body[0, 50] + '...' %>
      <%= link_to "show more", post, :class => 'btn btn-info'%></br>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div>
  <h1>New post</h1>
  <%= form_for :posts, url: { action: "create" } do |f| %>
    <div>
      <%= f.label :text, class: "col-sm-2 col-form-label" %>
      <%= f.text_field :text, class: "form-control", style: "border: 1px solid #ccc;" %>
    </div>
    <div style="margin-top: 10px;">
      <%= f.submit "Create", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<% if current_user %>
  <%= link_to "Logout", logout_path, method: :delete, class: "btn btn-success" %>
  <h1 class="text-center fs-1">My Posts</h1>
  <%= link_to "New post", new_post_path, class: "btn btn-success" %>
  <div class="row">
    <% @user.posts.each do |post| %>
      <div class="col-md-4 mb-4">
        <div class="card">
          <div class="card-body">
            <p class="card-text"><%= post.text %></p>
            <p class="card-text"><%= post.text.truncate(120) %></p>
            <%= link_to "Read more", post, class: "btn btn-primary" %>
            <%= link_to "Delete", post, method: :delete, class: "btn btn-warning" %>
            <%= link_to "Edit", edit_post_path(post), class: "btn btn-info" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <%= link_to "Login", login_path, class: "btn btn-success" %>
<% end %>

app/views/users/dashboard.html.erb
<h1>Личный кабинет</h1>
<% if @user %>
  <p>Привет, <%= @user.name %>!</p>
<% else %>
  <p>Данные пользователя не найдены</p>
<% end %>

app/views/users/edit.html.erb
<div class="d-flex align-items-center justify-content-center">
  <%= form_with model: User.recovery_password, method: :get do |form| %>
    <%= label_tag :password, "New Password", :class => 'form-label' %><br />
    <%= form.text_field :password, :class => 'form-control' %><br />
    <%= submit_tag "Update", :class => 'btn btn-primary' %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="m-5">
  <h1>Create new user</h1>
  <%= form_with model: User.new do |form| %>
    <%= label_tag :name, "Name", :class => 'form-label' %><br />
    <%= form.text_field :name, :class => 'form-control w-25' %><br />
    <%= label_tag :email, "Email Address", :class => 'form-label' %><br />
    <%= form.text_field :email, :class => 'form-control w-25' %><br />
    <%= label_tag :password, "Password", :class => 'form-label' %><br />
    <%= form.text_field :password, :class => 'form-control w-25' %><br />
    <%= submit_tag "Create", :class => 'btn btn-primary'%>
  <% end %>
</div>